#' Example of target protein data
#'
#' The data is generated by sampling procedure for showing the step-to-step application of the function.
#'
#' @format ## `X_EXAMPLE`
#' A vector of 5,000 elements.
"X_EXAMPLE"

#' Example of helper protein data
#'
#' This helper protein is correlated with `X_EXAMPLE`.
#'
#' @format ## `Y_EXAMPLE`
#' A vector of 5,000 elements.
#'
"Y_EXAMPLE"

#' Example of auxiliary protein data
#'
#' The data is generated by sampling procedure for showing the step-to-step application of the function.
#'
#' @format ## `Z_EXAMPLE`
#' A matrix with 5,000 rows and 200 columns.
#'
"Z_EXAMPLE"
